Add the category as first the first argument to all `Add*` methods
sunnyquiver/QPA2 pull request #46
Opened 2023-08-29 12:19 UTC by zickgraf

This change ensures compatibility with future versions of CAP.

Original commit by @TKuh

2023-08-30 13:01 UTC, mohamed-barakat commented on lib/module.gi
> +    cat!.category_as_first_argument := true;
this line is now obsolete

2023-08-30 13:02 UTC, mohamed-barakat requested changes
I suggest bumping the CAP version in the dependencies.

2023-08-30 13:29 UTC, zickgraf commented on lib/module.gi
> +    cat!.category_as_first_argument := true;
I think keeping compatibility with old versions of CAP far outweighs the benefits of removing this line.

2024-09-16 03:32 UTC, sunnyquiver approved these changes

2024-09-16 03:32 UTC, merged